// Generated by https://quicktype.io

export interface StackConfig {
    Services: Service[];
    Tasks:    Task[];
}

export interface Service {
    serviceName: string;
    pipeline:    Pipeline;
}

export interface Pipeline {
    name:        string;
    logGroup:    string;
    logStream:   string;
    github:      Github;
    codebuild:   Codebuild;
    ecrRepoName: string;
}

export interface Codebuild {
    projectName:          string;
    environmentVariables: EnvironmentVariable[];
}

export interface EnvironmentVariable {
    name:  string;
    value: string;
    type:  string;
}

export interface Github {
    owner:      string;
    repo:       string;
    secretName: string;
    cloneUrl:   string;
}

export interface Task {
    taskName: string;
    pipeline: Pipeline;
}
